### ISSUE TITLE
Why is UBSan enabled by default?

### ISSUE THREAD

**Issue by drfiemost** [libgme/game-music-emu#52]
I'd say it should be off for normal builds. If any it could be enabled when build type is Debug.

https://github.com/libgme/game-music-emu/blob/2212cdff42b5605d0191e743bf51299643dc2a55/CMakeLists.txt#L67C20-L67C20

**Comment by Wohlstand** [comment]
You right, ASAN/UBSAN should be enabled manually only for debugging only. In my main projects I already do that.

**Comment by Wohlstand** [comment]
Quickly fixed this.
