### ISSUE TITLE
use version script to export symbols?

### ISSUE THREAD

**Issue by sezero** [libgme/game-music-emu#62]
This is what we do in SDL's fork to hide C++ STL e.g. for Android:
https://developer.android.com/ndk/guides/middleware-vendors
https://github.com/libsdl-org/game-music-emu/blob/v0.6.3-SDL/gme/CMakeLists.txt#L266-L303
https://github.com/libsdl-org/game-music-emu/blob/v0.6.3-SDL/gme/gme.exports

If you are interested, I can create a PR for it.

**Comment by Wohlstand** [comment]
Ye, that would be useful.

**Comment by sezero** [comment]
OK, will send a patch shortly.
