### ISSUE TITLE
Android.mk is missing *.c sources

### ISSUE THREAD

**Issue by sezero** [libgme/game-music-emu#70]
Android.mk is missing gme/ext/*.c sources.

P.S.: The SDL fork has an Android.mk in v0.6.3-SDL branch -- here:
https://github.com/libsdl-org/game-music-emu/blob/v0.6.3-SDL/Android.mk
Maybe it's a good idea to sync things?

**Comment by Wohlstand** [comment]
Good idea. Mostly, there was no proper care about that script as modern Android projects do get built via CMake without of running Android.mk scripts. Ye, feel free to sync it up.

P.S. Maybe add the CI to verify the Android.mk build too?
