### ISSUE TITLE
Cleanup of the old Bitbucket repo?

### ISSUE THREAD

**Issue by purinchu** [libgme/game-music-emu#76]
@Wohlstand thanks for setting up this organization and repository.  You'll probably need to keep it going if libgme is going to keep progressing so please consider yourself fully blessed to run the project from here.

Since your account was deactivated at Bitbucket I wanted to ask, how should I tidy things up over there?  I can just shutdown that repository and a pointer to this one, but is there anything else you need taken care of over there that you didn't have permissions for before I do?

**Comment by Wohlstand** [comment]
Oh, finally, you came back! I'm glad you came back!

You may don't worry, everything that was on old repository has been synced up here, and all new changed now done here. You may freely delete the repository and put the link to here, or you may want to just alternate the README and Wiki to explain that the repository is **fully moved** (right now, they both tells that repository is **de-facto abandoned**), and just **archive** it for historical purposes (also, after importing of issues, some link IDs had been broken, and I am lazy yet to fix them up). 

By the way, as you can see, I made you being a co-owner here in this organisation, so, you still can continue to maintain the repository together with me.

**Comment by purinchu** [comment]
It was quite coincidental, but I was trying to swim through my thousands of unread emails and caught a subject line that the new repo had been created here. Followed the thread from here to see the repo had been migrated to get ahead of Bitbucket changes.

I did notice you've retained me as a co-owner and I'd be glad to pitch in where I can. Maybe more on build system stuff than the audio processing though :).

I'll archive the Bitbucket repo with a pointer back to here and we can wipe our hands clean of it.

**Comment by Wohlstand** [comment]
About the work with the sound, there are Me and several contribudors who understands a lot of deep stuff here.

By myself, I do like music since childhood, and in addition, I have my own related projects such as [libADLMIDI](https://github.com/Wohlstand/libADLMIDI) and [libOPNMIDI](https://github.com/Wohlstand/libOPNMIDI) projects that implements MIDI synthesizers over YMF262 and YM2612 chips.

**Comment by Wohlstand** [comment]
P.S. I see, you updated the ReadMe, however, the Wiki is still have an old message, could you update it too? https://bitbucket.org/mpyne/game-music-emu/wiki/Home

**Comment by purinchu** [comment]
Done!

**Comment by Wohlstand** [comment]
I also tweake the new Wiki, feel free to proofread it, and make any changed you think, are needed: https://github.com/libgme/game-music-emu/wiki
